<a href="https://colab.research.google.com/github/codewithhari98/Machine_Learning/blob/main/Neural_network_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
# Idea1: create a global w and b of size L which is number of layers
#https://www.youtube.com/watch?v=RSl87lqOXDE&ab_channel=CoreySchafer
#https://towardsdatascience.com/math-neural-network-from-scratch-in-python-d6da9f29ce654
#https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi
import numpy as np
class Layer:
  def __init__(self,inputsize,outputsize):
    self.input=inputsize
    self.output=outputsize
    self.weights = np.random.rand(inputsize, outputsize) - 0.5
    self.bias = np.random.rand(1, outputsize) - 0.5
  def forward_propagation(self, input):
    return -1
  def backward_propagation(self, output_error, learning_rate):
    return -1
    

4
weights:  [[-0.06840593  0.14503688 -0.08928376  0.15850501]
 [ 0.28367214  0.35226899  0.07809171 -0.37657678]
 [-0.19680188  0.35379274  0.05188079  0.13946606]
 [ 0.09220592  0.2172623  -0.29966389  0.42439393]
 [ 0.34807639  0.17512761  0.40682507 -0.4383075 ]]
bias:  [[ 0.01407155  0.18582692 -0.19935951  0.2375246 ]]


In [ ]:
class linearlayer(Layer):
  def forward_propagation(self,input):
    self.input_data=input
    f=np.dot(self.input_data, self.weights) + self.bias
    return f
  def backward_propagation(self,learning_rate,output_error):
    #diff of function f wrt weights gives input data 
    dfw=self.input_data
    dfx=self.weights
    #calculating sensitivity of cost wrt previous activation layer
    input_error = np.dot(output_error, dfx.T)
    #calculating sensitivity of cost wrt change in weights
    weights_error = np.dot(dfw.T, output_error)

    self.weights=self.weights-learning_rate*weights_error
    self.bias=self.bias-learning_rate*output_error
    #this returns the sensitivity of the cost func wrt previous activation func
    #which will be useful to calc the change in weights needed at inp
    return input_error

In [ ]:
class sigmoid(Layer):
  def 

In [ ]:
model1=linearlayer(5,4)
print(model1.output)
#model=Layer()
print("weights: ", model1.weights)
print("bias: ",model1.bias)